language: rust
cache:
  - cargo
rust:
  - stable
  - 1.15.0
  - beta
  - nightly

script:
  - make all
  - make travistest
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then make bench ; fi
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then cargo build --no-default-features; cargo test --no-default-features; fi

env:
  global:
    - RUST_BACKTRACE=1
  matrix:
    -
    - RELEASE=true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/87a331e1a21456b6e2ad
    on_success: change  # options: [always|never|change] default: always
    on_failure: change  # options: [always|never|change] default: always
    on_start: false     # default: false
