[default]
extend-ignore-re = [
    # support spellchecker directives (ideally this would be builtin)
    "(?Rm)^.*(#|//)\\s*spellchecker:ignore$",
    "(?s)(#|//)\\s*spellchecker:off.*?\\n\\s*(#|//)\\s*spellchecker:on",
]

[files]
ignore-hidden = false
extend-exclude = [
    ".git", # needed because we set 'ignore-hidden'
]

[default.extend-identifiers]
# the 'short' identifier for error
erro = "erro"
ERRO = "ERRO"
